stages:
  - build


.build_template:
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [ "" ]
  interruptible: true
  variables:
    DOCKER_CONFIG: /kaniko/.docker
    REGISTRY_USER: $CI_REGISTRY_USER
    REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    TAG: $CI_COMMIT_REF_NAME
  script:
    - |
      export SANITIZED_TAG="${CI_COMMIT_REF_NAME//\//-}"
      mkdir -p /kaniko/.docker
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$REGISTRY_USER\",\"password\":\"$REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

      DOCKERFILE="dockerfiles/coworking.goose.Dockerfile"  # Default to migrations
      case "${SERVICE_DIR}" in
        *"/go/"*) DOCKERFILE="dockerfiles/go.Dockerfile" ;;
        *"/rs/"*) DOCKERFILE="dockerfiles/rust.Dockerfile" ;;
      esac

      /kaniko/executor \
        --context "${CI_PROJECT_DIR}" \
        --dockerfile "${CI_PROJECT_DIR}/${DOCKERFILE}" \
        --destination "${CI_REGISTRY_IMAGE}/${SERVICE_NAME}:${SANITIZED_TAG}" \
        --build-arg "SERVICE=${SERVICE_NAME}" \
        --cache=true \
        --snapshot-mode=time \
        --registry-mirror=dockerhub.timeweb.cloud

  build-main-api-gateway:
    extends: .build_template
    stage: build
    rules:
    - when: always
    variables:
      SERVICE_DIR: "internal/gateways/main-api-gateway"
      SERVICE_NAME: "main-api-gateway"

  build-video-api-gateway:
    extends: .build_template
    stage: build
    rules:
      - when: always
    variables:
      SERVICE_DIR: "internal/gateways/video-api-gateway"
      SERVICE_NAME: "video-api-gateway"

  build-user-service:
    extends: .build_template
    stage: build
    rules:
      - when: always
    variables:
      SERVICE_DIR: "internal/services/user-service"
      SERVICE_NAME: "user-service"


  build-text-service:
    extends: .build-template
    stage: build
    rules:
      - when: always
    variables:
      SERVICE_DIR: "internal/services/text-service"
      SERVICE_NAME: "text-service"

    build-video-service:
      extends: .build-template
      stages: build
      rules:
        - when: always
      variables:
        SERVICE_DIR: "internal/services/video-service"
        SERVICE_NAME: "video-service"

    build-file-service:
      extends: .build-template
      stage: build
      rules:
        - when: always
      variables:
        SERVICE_DIR: "internal/services/file-service"
        SERVICE_NAME: "file-service"

