stages:
  - build

variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"  # Подключение к хостовому Docker

.build_template:
  stage: build
  image: docker:24.0.7  # Используем только Docker CLI
  script:
    - docker info  # Проверим, что Docker доступен
    - docker build -t "$SERVICE_NAME" "$SERVICE_DIR"
    - mkdir -p build
    - docker save "$SERVICE_NAME" -o "build/${SERVICE_NAME}.tar"
  artifacts:
    paths:
      - build/
    expire_in: 1 week

build-main-api-gateway:
  extends: .build_template
  variables:
    SERVICE_DIR: "internal/gateways/main-api-gateway"
    SERVICE_NAME: "main-api-gateway"

build-video-api-gateway:
  extends: .build_template
  variables:
    SERVICE_DIR: "internal/gateways/video-api-gateway"
    SERVICE_NAME: "video-api-gateway"

build-user-service:
  extends: .build_template
  variables:
    SERVICE_DIR: "internal/services/user-service"
    SERVICE_NAME: "user-service"

build-text-service:
  extends: .build_template
  variables:
    SERVICE_DIR: "internal/services/text-service"
    SERVICE_NAME: "text-service"

build-video-service:
  extends: .build_template
  variables:
    SERVICE_DIR: "internal/services/video-service"
    SERVICE_NAME: "video-service"

build-file-service:
  extends: .build_template
  variables:
    SERVICE_DIR: "internal/services/file-service"
    SERVICE_NAME: "file-service"
